# Generated by Django 2.1.5 on 2019-01-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='channel',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='web_hook',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
